/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Paneles.PanelJuridico;
import Paneles.PanelNatural;

/**
 *
 * @author Rosario
 */
public class PruebaPC2 extends javax.swing.JFrame {

    /**
     * Creates new form PruebaPC2
     */
    public PruebaPC2() {
        initComponents();
        PanelJuridico.setVisible(false);
        PanelNatural.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cli_jur = new javax.swing.JRadioButton();
        cli_nat = new javax.swing.JRadioButton();
        PanelJuridico = new Paneles.PanelJuridico();
        PanelNatural = new Paneles.PanelNatural();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FABRICA 'LA LECHERA'");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 11, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Queso", "S/.10.00", "Kilo", "8,000"},
                {"Leche", "S/.8.00", "Caja", "10,200"},
                {"Mantequilla", "S/.3.00", "Barra", "12,000"}
            },
            new String [] {
                "Tipo", "Precio", "Unidad", "Stock Actual"
            }
        ));
        jTable1.setToolTipText("");
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 43, 470, 78));

        jLabel2.setText("Informacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 24, -1, -1));

        jLabel3.setText("Comprador:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 143, -1, -1));

        buttonGroup1.add(cli_jur);
        cli_jur.setText("Cliente Juridico");
        cli_jur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_jurActionPerformed(evt);
            }
        });
        getContentPane().add(cli_jur, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 139, -1, -1));

        buttonGroup1.add(cli_nat);
        cli_nat.setText("Cliente Natural");
        cli_nat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cli_natActionPerformed(evt);
            }
        });
        getContentPane().add(cli_nat, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 139, -1, -1));
        getContentPane().add(PanelJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(PanelNatural, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cli_natActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_natActionPerformed
        if(cli_nat.isSelected()){
            PanelNatural.setVisible(true);
            PanelJuridico.setVisible(false);
        }
    }//GEN-LAST:event_cli_natActionPerformed

    private void cli_jurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cli_jurActionPerformed
        
        if(cli_jur.isSelected()){
            PanelNatural.setVisible(false);
            PanelJuridico.setVisible(true);
        }
        
        
            
       
       
    }//GEN-LAST:event_cli_jurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaPC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaPC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaPC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaPC2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaPC2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Paneles.PanelJuridico PanelJuridico;
    private Paneles.PanelNatural PanelNatural;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cli_jur;
    private javax.swing.JRadioButton cli_nat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
